// Auto-generated by scripts/generate_feature_registration.py - do not edit
#include "feature_registration.h"
#include "detour_manifest.h" // for feature_system_* calls

#include "features/console_overflow/detour_manifest.h"
#include "features/console_paste_fix/detour_manifest.h"
#include "features/media_timers/detour_manifest.h"
#include "features/ref_fixes/detour_manifest.h"
#include "features/scaled_font/detour_manifest.h"

// Queue features via FEATURE_AUTO_REGISTER
FEATURE_AUTO_REGISTER(console_overflow, "console_overflow", nullptr, nullptr, nullptr, &console_overflow_register_detours);
FEATURE_AUTO_REGISTER(console_paste_fix, "console_paste_fix", nullptr, nullptr, nullptr, &console_paste_fix_register_detours);
FEATURE_AUTO_REGISTER(media_timers, "media_timers", nullptr, nullptr, nullptr, &media_timers_register_detours);
FEATURE_AUTO_REGISTER(ref_fixes, "ref_fixes", nullptr, nullptr, nullptr, &ref_fixes_register_detours);
FEATURE_AUTO_REGISTER(scaled_font, "scaled_font", nullptr, nullptr, nullptr, &scaled_font_register_detours);
